// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/example.proto

package com.egoodhall.nrpc.example;

public interface EchoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EchoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
