// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/example.proto

package com.egoodhall.nrpc.example;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EchoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EchoReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025example/example.proto\"\036\n\013EchoRequest\022\017" +
      "\n\007message\030\001 \001(\t\"\034\n\tEchoReply\022\017\n\007message\030" +
      "\001 \001(\t22\n\016ExampleService\022 \n\004Echo\022\014.EchoRe" +
      "quest\032\n.EchoReplyBL\n\032com.egoodhall.nrpc." +
      "exampleP\001Z,github.com/egoodhall/nrpc/exa" +
      "mple/go;exampleb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EchoRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_EchoReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EchoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EchoReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
