// Code generated by nrpc; DO NOT EDIT.

package example

import (
	"errors"
	"strconv"

	"github.com/egoodhall/nrpc/go/pkg/nrpc"
	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/micro"
	"google.golang.org/protobuf/proto"
)

type EchoService interface {
	Echo(*EchoRequest) (*EchoReply, error)
}

func NewEchoServiceClient(conn *nats.Conn, options ...nrpc.ClientOption) (EchoService, error) {
	clientOptions, err := nrpc.NewClientOptions(options...)
	if err != nil {
		return nil, err
	}

	return &echoServiceClient{
		conn:    conn,
		options: clientOptions,
	}, nil
}

type echoServiceClient struct {
	options *nrpc.ClientOptions
	conn    *nats.Conn
}

func (client *echoServiceClient) Echo(request *EchoRequest) (*EchoReply, error) {
	data, err := proto.Marshal(request)
	if err != nil {
		return nil, err
	}

	resmsg, err := client.conn.Request(client.options.ApplyNamespace("EchoService.echo"), data, client.options.Timeout)
	if err != nil {
		return nil, err
	}

	if err := nrpc.ParseError(resmsg); err != nil {
		return nil, err
	}

	response := new(EchoReply)
	if err := proto.Unmarshal(resmsg.Data, response); err != nil {
		return nil, err
	}
	return response, nil
}

func NewEchoServiceServer(conn *nats.Conn, service EchoService, options ...nrpc.ServerOption) (nrpc.Server, error) {
	serverOptions, err := nrpc.NewServerOptions(options...)
	if err != nil {
		return nil, err
	}

	compat := &echoServiceServerCompat{
		options: serverOptions,
		service: service,
	}
	svc, err := micro.AddService(conn, micro.Config{
		Name:    "EchoService",
		Version: "0.0.0",
	})
	if err != nil {
		return nil, err
	}
	grp := serverOptions.ApplyNamespace(svc).AddGroup("EchoService")

	if err := grp.AddEndpoint("echo", micro.HandlerFunc(compat.serveEcho)); err != nil {
		svc.Stop()
		return nil, err
	}

	return svc, nil
}

type echoServiceServerCompat struct {
	options *nrpc.ServerOptions
	service EchoService
}

func (server *echoServiceServerCompat) handleError(err error) {
	if server.options.ErrorHandler != nil {
		server.options.ErrorHandler(err)
	}
}

func (server *echoServiceServerCompat) serveEcho(msg micro.Request) {
	request := new(EchoRequest)
	if err := proto.Unmarshal(msg.Data(), request); err != nil {
		msg.Error(strconv.Itoa(500), err.Error(), nil)
		server.handleError(err)
		return
	}

	response, err := server.service.Echo(request)
	if err != nil {
		e := new(nrpc.Error)
		if !errors.As(err, &e) {
			e = nrpc.NewError(500, err.Error())
		}

		msg.Error(strconv.Itoa(e.Code()), e.Error(), nil)
		server.handleError(err)
	}

	data, err := proto.Marshal(response)
	if err != nil {
		msg.Error(strconv.Itoa(500), err.Error(), nil)
		server.handleError(err)
		return
	}

	if err := msg.Respond(data); err != nil {
		server.handleError(err)
	}
}
