on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true

    - uses: actions/cache@v3
      with:
        path: gravel/cache.json
        key: ${{ github.ref_name }}-${{ github.event.after }}
        restore-keys: |
          ${{ github.ref_name }}-${{ github.event.before }}
          main-${{ github.event.before }}

    - run: go run github.com/egoodhall/gravel/cmd/gravel@latest build
