on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        version-file: go.mod
    - run: go generate ./...
    - run: go test ./...
    - run: go build ./cmd/nrpc
